[phases.setup]
nixPkgs = ["nodejs_20"]
cmds = ["corepack enable", "corepack prepare pnpm@10.29.3 --activate"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm build"]
