/**
 * N7 — Progress Token Prediction and Injection tests.
 */

import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import type { AnalysisContext } from "../../../../engine.js";
import type { EvidenceChain, EvidenceLink } from "../../../../evidence.js";
import "../index.js";
import { getTypedRuleV2 } from "../../../base.js";

const FIXTURES_DIR = join(__dirname, "..", "__fixtures__");

function loadFixture(name: string): string {
  return readFileSync(join(FIXTURES_DIR, name), "utf-8");
}

function ctx(src: string): AnalysisContext {
  return {
    server: { id: "t", name: "test", description: null, github_url: null },
    tools: [],
    source_code: src,
    dependencies: [],
    connection_metadata: null,
  };
}

function runN7(src: string) {
  const rule = getTypedRuleV2("N7");
  expect(rule).toBeDefined();
  return rule!.analyze(ctx(src));
}

function isStructuredTarget(t: string): boolean {
  return /^source_code:line \d+(:column \d+)?$/.test(t);
}

describe("N7 — Progress Token Prediction and Injection", () => {
  describe("true positives (CHARTER lethal edge cases)", () => {
    it("flags user-controlled token (user-controlled-token)", () => {
      const f = runN7(loadFixture("tp-user-controlled-token.ts"));
      expect(f.length).toBeGreaterThan(0);
    });

    it("flags sequential counter token (sequential-counter)", () => {
      const f = runN7(loadFixture("tp-sequential-counter.ts"));
      expect(f.length).toBeGreaterThan(0);
    });

    it("flags Date.now token (date-now-token)", () => {
      const f = runN7(loadFixture("tp-date-now-token.ts"));
      expect(f.length).toBeGreaterThan(0);
    });

    it("flags index-as-token via .indexOf", () => {
      const f = runN7(`const progressToken = items.indexOf(x); declare const items: any[]; declare const x: any;`);
      expect(f.length).toBeGreaterThan(0);
    });
  });

  describe("true negatives", () => {
    it("does NOT flag crypto.randomUUID token", () => {
      expect(runN7(loadFixture("tn-crypto-random-token.ts"))).toHaveLength(0);
    });

    it("does NOT flag token generated by crypto even when user input is in scope", () => {
      expect(runN7(loadFixture("tn-validated-against-map.ts"))).toHaveLength(0);
    });

    it("does NOT flag non-progress identifier increments", () => {
      expect(runN7(`let counter = 0; counter++;`)).toHaveLength(0);
    });
  });

  describe("evidence chain shape", () => {
    it("user-input source produces session-hijack impact with trivial exploitability", () => {
      const findings = runN7(loadFixture("tp-user-controlled-token.ts"));
      const chain = (findings[0] as unknown as { chain: EvidenceChain }).chain;
      const impact = chain.links.find((l) => l.type === "impact") as any;
      expect(impact.impact_type).toBe("session-hijack");
      expect(impact.exploitability).toBe("trivial");
    });

    it("predictable-generator source produces denial-of-service impact", () => {
      const findings = runN7(loadFixture("tp-date-now-token.ts"));
      const chain = (findings[0] as unknown as { chain: EvidenceChain }).chain;
      const impact = chain.links.find((l) => l.type === "impact") as any;
      expect(impact.impact_type).toBe("denial-of-service");
    });

    it("chain includes source + propagation + sink + impact", () => {
      const findings = runN7(loadFixture("tp-user-controlled-token.ts"));
      const chain = (findings[0] as unknown as { chain: EvidenceChain }).chain;
      const kinds = new Set(chain.links.map((l: EvidenceLink) => l.type));
      expect(kinds.has("source")).toBe(true);
      expect(kinds.has("propagation")).toBe(true);
      expect(kinds.has("sink")).toBe(true);
      expect(kinds.has("impact")).toBe(true);
    });

    it("confidence respects CHARTER ceiling (≤ 0.88)", () => {
      const findings = runN7(loadFixture("tp-user-controlled-token.ts"));
      const chain = (findings[0] as unknown as { chain: EvidenceChain }).chain;
      expect(chain.confidence).toBeLessThanOrEqual(0.88);
    });

    it("verification step targets are structured", () => {
      const findings = runN7(loadFixture("tp-user-controlled-token.ts"));
      const chain = (findings[0] as unknown as { chain: EvidenceChain }).chain;
      for (const step of chain.verification_steps ?? []) {
        expect(isStructuredTarget(step.target)).toBe(true);
      }
    });

    it("required factor 'weak_progress_token_source' is present", () => {
      const findings = runN7(loadFixture("tp-sequential-counter.ts"));
      const chain = (findings[0] as unknown as { chain: EvidenceChain }).chain;
      expect(chain.confidence_factors.map((f) => f.factor)).toContain(
        "weak_progress_token_source",
      );
    });
  });
});
