"use client";
/**
 * §8 Evidence Trust Panel — runtime analysis statement, e2e chain
 * preservation status, and the per-finding signed receipt URL pattern.
 *
 * The receipt endpoint already exists at GET /api/v1/findings/:id/receipt
 * (RFC 8785 canonicalised + HMAC-SHA256 signed via signFinding from
 * @mcp-sentinel/compliance-reports). This panel is the one place on the
 * page that explains the "every claim is verifiable" posture in prose,
 * with a verify-command hint matching ForensicDrawer's Receipt tab UX.
 */

import React from "react";
import type { AuditEvidenceTrust } from "@/lib/deep-dive";

export default function EvidenceTrustPanel({
  trust,
  apiOrigin,
}: {
  trust: AuditEvidenceTrust | null | undefined;
  /** API origin (e.g. https://api.mcp-sentinel.com) for the receipt URL. */
  apiOrigin: string;
}) {
  if (!trust) {
    return (
      <section
        className="audit-panel audit-panel-trust audit-panel-empty"
        aria-label="Evidence trust — not on file"
      >
        <p className="audit-panel-empty-text">
          Evidence trust signals have not been derived for this scan.
        </p>
      </section>
    );
  }

  const fullPattern = `${apiOrigin.replace(/\/$/, "")}${trust.receipt_url_pattern}`;

  return (
    <section
      className="audit-panel audit-panel-trust"
      aria-label="Evidence trust"
    >
      <header className="audit-section-head">
        <h3 className="audit-section-title">Evidence trust</h3>
      </header>

      <ul className="audit-trust-claims" aria-label="Trust claims">
        <li className="audit-trust-claim">
          <span
            className={`audit-trust-glyph ${trust.runtime_analysis ? "audit-trust-yes" : "audit-trust-no"}`}
            aria-hidden="true"
          >
            {trust.runtime_analysis ? "✓" : "✗"}
          </span>
          <span className="audit-trust-text">
            <strong>Runtime analysis.</strong> Every finding is generated by
            deterministic source-to-sink analysis at scan time — never by an
            LLM (per ADR-006).
          </span>
        </li>
        <li className="audit-trust-claim">
          <span
            className={`audit-trust-glyph ${trust.e2e_chain_preserved ? "audit-trust-yes" : "audit-trust-no"}`}
            aria-hidden="true"
          >
            {trust.e2e_chain_preserved ? "✓" : "✗"}
          </span>
          <span className="audit-trust-text">
            <strong>End-to-end evidence chain preserved.</strong>{" "}
            {trust.e2e_chain_preserved
              ? "Every persisted finding carries the structured EvidenceChain (source → propagation → sink → mitigation → impact) that the rule produced."
              : "At least one finding lacks an evidence chain — the verdict is degraded for this server. Investigate which rule emitted a chainless finding."}
          </span>
        </li>
        <li className="audit-trust-claim">
          <span className="audit-trust-glyph audit-trust-yes" aria-hidden="true">
            ◆
          </span>
          <span className="audit-trust-text">
            <strong>Verifiable via signed receipt.</strong> Every finding can be
            independently verified — fetch the receipt below, recompute the
            HMAC-SHA256, compare to the signature header.
          </span>
        </li>
      </ul>

      <details className="audit-trust-receipt">
        <summary className="audit-trust-receipt-summary">
          Receipt URL pattern + verify command
        </summary>
        <div className="audit-trust-receipt-body">
          <div className="audit-trust-receipt-row">
            <span className="audit-trust-receipt-label">Receipt URL</span>
            <code className="audit-trust-receipt-code">{fullPattern}</code>
          </div>
          <div className="audit-trust-receipt-row">
            <span className="audit-trust-receipt-label">Algorithm</span>
            <code className="audit-trust-receipt-code">HMAC-SHA256</code>
          </div>
          <div className="audit-trust-receipt-row">
            <span className="audit-trust-receipt-label">Canonicalisation</span>
            <code className="audit-trust-receipt-code">RFC 8785 (JSON Canonicalization Scheme)</code>
          </div>
          <p className="audit-trust-receipt-hint">
            Replace <code>:id</code> with any finding id from this page (visible
            on each finding panel) to fetch its signed receipt. The signature
            is in the <code>X-MCP-Sentinel-Signature</code> response header.
          </p>
        </div>
      </details>
    </section>
  );
}
